server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: /mapper/**.xml


jwt:
  # 发行者
  name: ADROITWOLF
  # 密钥, 经过Base64加密,去等 可自行替换 默认development
  base64Secret: ZGV2ZWxvcG1lbnQ
  #jwt中过期时间设置(s)
  jwtExpires: 2000
  # refresh过期时间(day)
  refreshExpires: 5
